spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:mysql://localhost:3306/task_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Automatically update table structure
    show-sql: true # show SQL statements
    properties:
      hibernate:
        format_sql: true # format SQL statements
