server:
  port: 8888

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          # Enable automatic routing based on service discovery
          enabled: true
          lower-case-service-id: true
      routes:
        - id: task-manager
          uri: lb://task-manager
          predicates:
            - Path=/task-manager/**
          filters:
            - RewritePath=/task-manager/(?<segment>.*), /${segment}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
