server:
  port: 8080

spring:
  application:
    name: task-manager
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
    url: jdbc:mysql://localhost:3306/task_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically update table structure
    show-sql: true # show SQL statements
    properties:
      hibernate:
        format_sql: true # format SQL statements

springdoc:
  swagger-ui:
    path: /docs         # Access URL becomes http://localhost:8080/docs
  api-docs:
    path: /openapi.json # Raw JSON URL http://localhost:8080/openapi.json

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
    instances:
      userClientHello:
        base-config: default